Use bevy_http_client instead of reqwest
Otherwise I was getting "thread 'IO Task Pool (3)' panicked at ... there is no reactor running, must be called from the context of a Tokio 1.x runtime"